version: '3.8'
services:
  pg_polygon:
    image: postgres:15.4
    restart: always
    ports:
      - 1234:5432
    volumes:
        - ./pg_data:/var/lib/postgresql/data
    env_file:
      - creds.polygon.env
  pg_cardano:
    image: postgres:15.4
    restart: always
    ports:
      - 1235:5432
    volumes:
        - ./pg_data_cardano:/var/lib/postgresql/data
    env_file:
      - creds.cardano.env
  bor:
    image: shockedshodan/zombie-bor:latest
    restart: always
    command:
      - server
      - --datadir=/datadir
      - --port=30303
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.port=8545
      - --ipcpath=/datadir/bor.ipc
      - --http.api=eth,net,web3,txpool,bor
      - --syncmode=full
      - --miner.gasprice=30000000000
      - --miner.gaslimit=30000000
      - --txpool.nolocals
      - --txpool.accountslots=16
      - --txpool.globalslots=32768
      - --txpool.accountqueue=16
      - --txpool.globalqueue=32768
      - --txpool.pricelimit=30000000000
      - --txpool.lifetime=1h30m0s
      - --gpo.ignoreprice=30000000000
      - --maxpeers=400
      - --metrics
      - --bootnodes=enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303
    volumes:
      - ./bor_datadir:/datadir
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 30303:30303
      - 30303:30303/udp
    depends_on:
      - backend_polygon
    env_file:
      - creds.polygon.env
  backend_polygon:
    restart: always
    depends_on:
      - pg_polygon
    build: ./backend
    ports:
      - 5500:5500
    command: ["poetry", "run", "python", "-m", "polydash", "-s", "polygon.yaml", "polygon" ]
  backend_cardano:
    restart: always
    depends_on:
      - pg_cardano
    build: ./backend
    ports:
      - 5501:5500
    command: ["poetry", "run", "python", "-m", "polydash", "-s", "cardano.yaml", "cardano"]
